// Katalog skill badge rekomendasi fasilitator 2026 (nama resmi EN + course id).
// Sumber: silabus rsvp.withgoogle.com/events/arcade-fasilitator-id + skills.google course titles.
export const SKILL_CATALOG = [
  { id: 1586, name: 'Create Your First Gemini Enterprise Application' },
  { id: 1426, name: 'Develop AI-Powered Prototypes in Google AI Studio' },
  { id: 754, name: 'The Basics of Google Cloud Compute' },
  { id: 728, name: 'Implement Event-Driven Messaging and Automation Workflows' },
  { id: 725, name: 'Implement Cloud Storage and Data Protection Solutions' },
  { id: 705, name: 'Create a Streaming Data Lake on Cloud Storage' },
  { id: 671, name: 'Deploy and Manage Applications on Google App Engine' },
  { id: 700, name: 'Implement Speech and Language Solutions with Pre-trained APIs' },
  { id: 756, name: 'Using the Google Cloud Speech API' },
  { id: 634, name: 'Analyze Speech and Language with Google APIs' },
  { id: 658, name: 'Store, Process, and Manage Data on Google Cloud - Console' },
  { id: 659, name: 'Store, Process, and Manage Data on Google Cloud - Command Line' },
  { id: 629, name: 'Migrate MySQL Data to Cloud SQL Using Database Migration Service' },
  { id: 750, name: 'Get Started with Sensitive Data Protection' },
  { id: 633, name: 'Analyze Images with the Cloud Vision API' },
  { id: 727, name: 'Build Event-Driven Applications with Eventarc' },
  { id: 702, name: 'Configure Service Accounts and IAM Roles for Google Cloud' },
  { id: 1596, name: 'Engineer AI Agents with Agent Development Kit (ADK)' },
  { id: 1076, name: 'Build Real World AI Applications with Gemini and Imagen' },
  { id: 1459, name: 'Build a Smart Cloud Application with Vibe Coding and MCP' },
  { id: 676, name: 'Implement Cloud Collaboration and Productivity Workflows' },
  { id: 632, name: 'Analyze BigQuery Data in Connected Sheets' },
  { id: 752, name: 'Streaming Analytics into BigQuery' },
  { id: 704, name: 'Create a Secure Data Lake on Cloud Storage' },
  { id: 751, name: 'Secure Lakehouse Data' },
  { id: 753, name: 'Enrich Metadata and Discovery of Lakehouse Data' },
  { id: 653, name: 'Monitor and Manage Google Cloud Resources' },
  { id: 749, name: 'Monitor and Log with Google Cloud Observability' },
  { id: 641, name: 'Set Up a Google Cloud Network' },
  { id: 737, name: 'Integrate BigQuery Data and Google Workspace using Apps Script' },
  { id: 627, name: 'Engineer Data for Predictive Modeling with BigQuery ML' },
  { id: 716, name: 'Implement DevOps Workflows in Google Cloud' },
  { id: 626, name: 'Create ML Models with BigQuery ML' },
  { id: 638, name: 'Build a Website on Google Cloud' },
  { id: 959, name: 'Explore Generative AI in Agent Platform' },
  { id: 648, name: 'Implementing Cloud Load Balancing for Compute Engine' },
  { id: 976, name: 'Prompt Design in Agent Platform' },
  { id: 981, name: 'Inspect Rich Documents with Gemini Multimodality and Multimodal RAG' },
  { id: 978, name: 'Develop Gen AI Apps with Gemini and Streamlit' },
  { id: 637, name: 'Set Up an App Dev Environment on Google Cloud' },
  { id: 625, name: 'Develop Your Google Cloud Network' },
  { id: 654, name: 'Build a Secure Google Cloud Network' },
  { id: 663, name: 'Deploy Kubernetes Applications on Google Cloud' },
  { id: 623, name: 'Derive Insights from BigQuery Data' },
  { id: 639, name: 'Build LookML Objects in Looker' },
  { id: 651, name: 'Manage Data Models in Looker' },
  { id: 628, name: 'Prepare Data for Looker Dashboards and Reports' },
  { id: 649, name: 'Develop Serverless Apps with Firebase' },
  { id: 640, name: 'Cloud Architecture: Design, Implement, and Manage' },
  { id: 1558, name: 'Build Global and Regional Load Balancing Solutions' },
  { id: 1453, name: 'Google DeepMind: Train A Small Language Model' },
]

export const GAME_CATALOG = [
  { name: 'Arcade Base Camp', img: '/img/game-basecamp.png', re: /base ?camp/i },
  { name: 'Arcade Adventure', img: '/img/game-adventure.png', re: /adventure/i },
  { name: 'Arcade Voyage', img: '/img/game-voyage.png', re: /voyage/i },
  { name: 'Arcade Trail', img: '/img/game-trail.png', re: /trail/i },
  { name: 'Arcade Special', img: '/img/game-special.png', re: /special|safe space/i },
  { name: 'New Arcade Game', img: '/img/game-new.png', re: /simulator|new game|data mesh/i },
]

const UTM = '?utm_source=arcade-hub'
export const courseUrl = (id) => `https://www.skills.google/course_templates/${id}${UTM}`
export const norm = (s) => (s || '').toLowerCase().replace(/[^a-z0-9]+/g, '')
