// Katalog COMPLETION BADGE Google Skills. DIBUAT OTOMATIS, jangan sunting tangan:
// jalankan `npm run scrape:completion` lalu baca diff-nya.
//
// Completion badge = badge dari course biasa (bukan skill badge berbasis lab). Sumber:
// skills.google/catalog dengan filter Format = Course, ambil yang `credentialType` null.
// `min` = perkiraan durasi resmi dalam menit, dipakai mengurutkan dari yang tercepat.
//
// Catatan poin: silabus resmi fasilitator menyebut "Badge Keahlian". Tracker ini menghitung
// SEMUA badge non-game yang di-earn di periode program sebagai badge keahlian (lihat
// lib/parseProfile.js), jadi completion badge ikut terhitung 2 badge = 1 poin. Daftar ini
// membuat katalog cocok dengan cara skor itu dihitung, bukan menambah aturan baru.
//
// Ada dua entri berjudul sama persis (1146 dan 1147, "Introduction to Security in the World
// of AI"). Itu memang dua course terpisah di Google dan keduanya bisa di-earn, jadi keduanya
// sengaja dipertahankan.
export const COMPLETION_CATALOG = [
  { id: 20, name: 'Building Scalable Java Microservices with Spring Boot and Spring Cloud', min: 5 },
  { id: 1349, name: 'AI Boost Bites: Gemini Gems – Your ultimate marketing sidekick', min: 10 },
  { id: 1350, name: 'AI Boost Bites: Amplify Exec Voices with AI', min: 10 },
  { id: 1351, name: 'AI Boost Bites: No-Code Sheets & Scripts', min: 10 },
  { id: 1353, name: 'AI Boost Bites: Gemini Image-to-Sheets Hack', min: 10 },
  { id: 1355, name: 'AI Boost Bites: Exec Summaries with Gemini Gems', min: 10 },
  { id: 1357, name: 'AI Boost Bites: TL;DR with Gemini in Docs & Drive', min: 10 },
  { id: 1363, name: 'AI Boost Bites: Poke Holes in Your Strategy', min: 10 },
  { id: 1365, name: 'AI Boost Bites: Prompting like a Pro with Google Workspace', min: 10 },
  { id: 1366, name: 'AI Boost Bites: Personalization with customized prompts', min: 10 },
  { id: 1367, name: 'AI Boost Bites: Gemini Slide Summaries', min: 10 },
  { id: 1369, name: 'AI Boost Bites: Content Generation with Gemini Made Easy', min: 10 },
  { id: 1371, name: 'AI Boost Bites: Automate tasks with Gemini and Apps Script', min: 10 },
  { id: 1416, name: 'AI Boost Bites: Tame Your Inbox with AI', min: 10 },
  { id: 1419, name: 'AI Boost Bites: Create Docs in Seconds', min: 10 },
  { id: 1421, name: 'AI Boost Bites: Email Content Creation', min: 10 },
  { id: 1433, name: 'AI Boost Bites: Presentation Scripts with Gemini', min: 10 },
  { id: 1449, name: 'AI Boost Bites: Your Personal Feedback Agent', min: 10 },
  { id: 1467, name: 'AI Boost Bites: Create Your Own Retro Arcade Game', min: 10 },
  { id: 1468, name: 'AI Boost Bites: Gamify Your Study Guides', min: 10 },
  { id: 1471, name: 'AI Boost Bites: Create Your Ultimate College Scouting Report', min: 10 },
  { id: 1472, name: 'AI Boost Bites: Build a Personalized Weather App', min: 10 },
  { id: 1473, name: 'AI Boost Bites: Animated Charts with Gemini', min: 10 },
  { id: 1474, name: 'AI Boost Bites: Become an AI Art Director for Your World', min: 10 },
  { id: 1476, name: 'AI Boost Bites: Create Your Own Productivity Tools', min: 10 },
  { id: 1477, name: 'AI Boost Bites: Make Any Big Purchase with Confidence', min: 10 },
  { id: 1479, name: 'AI Boost Bites: Advanced Analysis in Sheets', min: 10 },
  { id: 1480, name: 'AI Boost Bites: From Napkin Sketch to Functional App', min: 10 },
  { id: 1481, name: 'AI Boost Bites: Guided Learning with Gemini', min: 10 },
  { id: 1482, name: 'AI Boost Bites: Your Personal AI Tutor', min: 10 },
  { id: 1484, name: 'AI Boost Bites: Talk to Your Data in Sheets', min: 10 },
  { id: 1485, name: 'AI Boost Bites: One-Click Campaign Visuals', min: 10 },
  { id: 1486, name: 'AI Boost Bites: Turn Your Ideas into Animated Art', min: 10 },
  { id: 1487, name: 'AI Boost Bites: AI Magic in a Sheets Cell', min: 10 },
  { id: 1488, name: 'AI Boost Bites: Create a 3D Solar System', min: 10 },
  { id: 1489, name: 'AI Boost Bites: Notes to Sheets with Gemini', min: 10 },
  { id: 1490, name: 'AI Boost Bites: Streamline Event Planning with AI', min: 10 },
  { id: 1491, name: 'AI Boost Bites: Create the Perfect Portrait', min: 10 },
  { id: 1492, name: 'AI Boost Bites: Become a Creative Mashup Artist', min: 10 },
  { id: 1493, name: 'AI Boost Bites: Become a "Vibe DJ"', min: 10 },
  { id: 1494, name: 'AI Boost Bites: Get Your Competitor\'s Playbook in Minutes', min: 10 },
  { id: 1495, name: 'AI Boost Bites: Gemini Calendar Hacks in Gmail', min: 10 },
  { id: 1498, name: 'AI Boost Bites: Supercharge Research with Gemini', min: 10 },
  { id: 1499, name: 'AI Boost Bites: Build Slides Fast with Gemini', min: 10 },
  { id: 1601, name: 'AI Boost Bites: Become a Homework Hero for Your Kids', min: 10 },
  { id: 1602, name: 'AI Boost Bites: Your AI Chart Detective', min: 10 },
  { id: 1604, name: 'AI Boost Bites: Presentations in Seconds with Nano Banana Pro', min: 10 },
  { id: 1605, name: 'AI Boost Bites: Shareable Gems', min: 10 },
  { id: 1606, name: 'AI Boost Bites: Triage a Crisis with Gemini', min: 10 },
  { id: 1609, name: 'AI Boost Bites: Build Charts with a Prompt', min: 10 },
  { id: 1611, name: 'AI Boost Bites: Bring your photos to life with AI', min: 10 },
  { id: 1613, name: 'AI Boost Bites: Build Your AI Strategic Partner', min: 10 },
  { id: 1617, name: 'AI Boost Bites: The Recruiter\'s Playbook in Gmail', min: 10 },
  { id: 1766, name: 'Welcome to the AI for Nonprofits Course Series', min: 10 },
  { id: 1769, name: 'GEAR: Introduction to Agents and Google’s Agent Ecosystem', min: 10 },
  { id: 1770, name: 'GEAR: Deploy Production-Ready Agents', min: 10 },
  { id: 1771, name: 'Wrap Up: Develop Agents with ADK', min: 10 },
  { id: 1772, name: 'Wrap Up: Introduction to Agents and Google’s Agent Ecosystem', min: 10 },
  { id: 1773, name: 'Wrap Up: Deploy Production-Ready Agents', min: 10 },
  { id: 1776, name: 'GEAR: Scale Agents Across the Enterprise', min: 10 },
  { id: 1777, name: 'Wrap Up: Scale Agents Across the Enterprise', min: 10 },
  { id: 1778, name: 'GEAR: Develop Agents with Agent Development Kit (ADK)', min: 10 },
  { id: 554, name: 'Introduction to Responsible AI', min: 15 },
  { id: 1575, name: 'Introduction to GKE Networking', min: 15 },
  { id: 1643, name: 'Human-Centered AI', min: 15 },
  { id: 537, name: 'Attention Mechanism', min: 30 },
  { id: 538, name: 'Transformer Models and BERT Model', min: 30 },
  { id: 541, name: 'Introduction to Image Generation', min: 30 },
  { id: 542, name: 'Create Image Captioning Models', min: 30 },
  { id: 543, name: 'Encoder-Decoder Architecture', min: 30 },
  { id: 888, name: 'Google Workspace with Gemini: Foundations of Your AI Workflow', min: 30 },
  { id: 896, name: 'Gemini in Gmail', min: 30 },
  { id: 905, name: 'Gemini in Google Sheets', min: 30 },
  { id: 914, name: 'Gemini in Google Docs', min: 30 },
  { id: 927, name: 'Machine Learning Operations (MLOps) for Generative AI', min: 30 },
  { id: 931, name: 'Gemini in Google Slides', min: 30 },
  { id: 943, name: 'Gemini in Google Meet', min: 30 },
  { id: 1135, name: 'Gemini in Google Drive', min: 30 },
  { id: 1202, name: 'Introduction to Cloud Next Generation Firewall', min: 30 },
  { id: 1583, name: 'Introduction to AI Agents', min: 30 },
  { id: 1585, name: 'Build Agents with Agent Development Kit (ADK)', min: 30 },
  { id: 1630, name: 'Fundamentals of Google\'s Arm-based Axion Processors', min: 30 },
  { id: 1783, name: 'Gemini in Google Chat', min: 30 },
  { id: 1833, name: 'Build Collaborative Multi-Agent Systems with ADK & MCP', min: 30 },
  { id: 1835, name: 'Secure Enterprise AI Agents', min: 30 },
  { id: 383, name: 'Build a Certification Study Guide: PCNE Exam Prep', min: 45 },
  { id: 536, name: 'Introduction to Generative AI', min: 45 },
  { id: 886, name: 'Gemini for Security Engineers', min: 45 },
  { id: 1179, name: 'Create Engaging Video with Google Vids', min: 45 },
  { id: 1430, name: 'Network Observability on Google Cloud', min: 45 },
  { id: 1460, name: 'Future-Proof Your AI Learning Strategy', min: 45 },
  { id: 1633, name: 'Build and Deploy Agents in Production', min: 45 },
  { id: 1738, name: 'AI Boost Bootcamp: How to Use Gemini for Marketing 201', min: 45 },
  { id: 1830, name: 'Critical Thinking in AI-Driven Workflows', min: 45 },
  { id: 77, name: 'Build a Certification Study Guide: ACE Exam Prep', min: 60 },
  { id: 78, name: 'Build a Certification Study Guide: PCA Exam Prep', min: 60 },
  { id: 168, name: 'Managing and Securing the Apigee Hybrid API Platform', min: 60 },
  { id: 170, name: 'Running SAP Workloads on Google Cloud: Fundamentals', min: 60 },
  { id: 539, name: 'Introduction to Large Language Models', min: 60 },
  { id: 734, name: 'Google Cloud Solutions I: Scaling Your Infrastructure', min: 60 },
  { id: 878, name: 'Gemini for Cloud Architects', min: 60 },
  { id: 884, name: 'Gemini for Network Engineers', min: 60 },
  { id: 1044, name: 'Cloud Retail Search Quiz', min: 60 },
  { id: 1081, name: 'Generative AI for Healthcare', min: 60 },
  { id: 1146, name: 'Introduction to Security in the World of AI', min: 60 },
  { id: 1147, name: 'Introduction to Security in the World of AI', min: 60 },
  { id: 1171, name: 'Build a Certification Study Guide: PMLE', min: 60 },
  { id: 1178, name: 'Unleash Team Potential: Assess Learning Needs Using GenAI', min: 60 },
  { id: 1194, name: 'Quiz: GDC Air-Gapped Practitioner Fundamentals', min: 60 },
  { id: 1196, name: 'Quiz: GDC Air-Gapped Security Operator Fundamentals', min: 60 },
  { id: 1203, name: 'Plan Your Cloud Next Generation Firewall Needs', min: 60 },
  { id: 1265, name: 'Gen AI: Unlock Foundational Concepts', min: 60 },
  { id: 1403, name: 'AI Infrastructure: Cloud GPUs', min: 60 },
  { id: 1404, name: 'AI Infrastructure: Introduction to AI Hypercomputer', min: 60 },
  { id: 1405, name: 'AI Infrastructure: Cloud TPUs', min: 60 },
  { id: 1406, name: 'Introduction to Google Distributed Cloud Sandbox', min: 60 },
  { id: 1456, name: 'Build a Certification Study Guide: PSOE Exam Prep', min: 60 },
  { id: 1516, name: 'How to Use TPUs for Inference', min: 60 },
  { id: 1517, name: 'Architecting an AI Inference Stack', min: 60 },
  { id: 1520, name: 'Build a Certification Study Guide: PCDBE Exam Prep', min: 60 },
  { id: 1552, name: 'AI Infrastructure: Networking Techniques', min: 60 },
  { id: 1553, name: 'AI Infrastructure: Storage Options', min: 60 },
  { id: 1563, name: 'Build Your First Agent with Agent Development Kit (ADK)', min: 60 },
  { id: 1564, name: 'Optimize Agent Behavior', min: 60 },
  { id: 1584, name: 'Manage Agent Memory and State', min: 60 },
  { id: 1593, name: 'Add Agent Capabilities With Tools', min: 60 },
  { id: 1597, name: 'Digital Sovereignty with Google Cloud', min: 60 },
  { id: 1620, name: 'AI for Data Analysis', min: 60 },
  { id: 1621, name: 'AI for App Building', min: 60 },
  { id: 1622, name: 'AI for Research and Insights', min: 60 },
  { id: 1623, name: 'AI for Brainstorming and Planning', min: 60 },
  { id: 1624, name: 'AI for Content Creation', min: 60 },
  { id: 1625, name: 'AI for Writing and Communicating', min: 60 },
  { id: 1645, name: 'Coordinate Multiple Agents', min: 60 },
  { id: 1660, name: 'Orchestrate Complex Multi-Agent Workflows', min: 60 },
  { id: 1674, name: 'AI Boost Bootcamp: How to Use Gemini at Work 101', min: 60 },
  { id: 1678, name: 'Add Agent Guardrails with Callbacks', min: 60 },
  { id: 1679, name: 'Running Oracle Workloads on Google Cloud: Fundamentals', min: 60 },
  { id: 1825, name: 'Set Up Multiple Network Interfaces', min: 60 },
  { id: 1831, name: 'Simplify Your Architecture with Network Connectivity Center', min: 60 },
  { id: 265, name: 'Modernize Infrastructure and Applications with Google Cloud', min: 75 },
  { id: 266, name: 'Digital Transformation with Google Cloud', min: 75 },
  { id: 271, name: 'Scaling with Google Cloud Operations', min: 75 },
  { id: 882, name: 'Gemini for DevOps Engineers', min: 75 },
  { id: 1108, name: 'Conversational AI and its Engagement Framework', min: 75 },
  { id: 1122, name: 'Create Agents with Generative Playbooks', min: 75 },
  { id: 1206, name: 'Essential Google Cloud CLI Tools', min: 75 },
  { id: 1261, name: 'Gen AI: Navigate the Landscape', min: 75 },
  { id: 1347, name: 'Deploy and Scale AI Models with Cloud Run', min: 75 },
  { id: 1639, name: 'Deploy Your First Agent', min: 75 },
  { id: 1763, name: 'Build Smarter Workflows with AI for Nonprofits', min: 75 },
  { id: 1765, name: 'Optimize Creativity and Fundraising with AI for Nonprofits', min: 75 },
  { id: 97, name: 'Managing Change when Moving to Google Cloud', min: 90 },
  { id: 267, name: 'Exploring Data Transformation with Google Cloud', min: 90 },
  { id: 619, name: 'Baseline: Data, ML, AI', min: 90 },
  { id: 665, name: 'Applying Advanced LookML Concepts in Looker', min: 90 },
  { id: 775, name: 'Understand Your Google Cloud Costs', min: 90 },
  { id: 881, name: 'Gemini for Application Developers', min: 90 },
  { id: 885, name: 'Gemini for end-to-end SDLC', min: 90 },
  { id: 944, name: 'Handle Consumer Interactions with CCaaS', min: 90 },
  { id: 946, name: 'Innovating with Google Cloud Artificial Intelligence', min: 90 },
  { id: 1070, name: 'Conversation Design Fundamentals', min: 90 },
  { id: 1268, name: 'Gen AI: Beyond the Chatbot', min: 90 },
  { id: 1402, name: 'Configure Gemini Code Assist for Organizations', min: 90 },
  { id: 1437, name: 'Architect Gemini Enterprise for Customer Experience', min: 90 },
  { id: 1441, name: 'Security Command Center: Identify and Prioritize Risks', min: 90 },
  { id: 1505, name: 'Web and Mobile Anti-fraud Defense', min: 90 },
  { id: 1554, name: 'AI Infrastructure: Deployment Types', min: 90 },
  { id: 1561, name: 'Migrating to Google Cloud: Fundamentals', min: 90 },
  { id: 1562, name: 'Agent Fundamentals', min: 90 },
  { id: 1587, name: 'Enterprise Agents and Use Cases', min: 90 },
  { id: 1661, name: 'Build a Certification Study Guide: PCD Exam Prep', min: 90 },
  { id: 1691, name: 'Build a Certification Study Guide: PCDOE Exam Prep', min: 90 },
  { id: 1736, name: 'Design and Implement Network Security in Google Cloud', min: 90 },
  { id: 1762, name: 'Scaling Data Science with Agents', min: 90 },
  { id: 1764, name: 'Daily Wins with AI for Nonprofits', min: 90 },
  { id: 226, name: 'The Modern Data Platform and LookML', min: 105 },
  { id: 735, name: 'Google Developer Essentials', min: 105 },
  { id: 782, name: 'Workspace: Integrations for Data', min: 105 },
  { id: 953, name: 'Security Command Center Fundamentals', min: 105 },
  { id: 971, name: 'Google Security Operations - Fundamentals', min: 105 },
  { id: 972, name: 'Google Security Operations - Deep Dive', min: 105 },
  { id: 980, name: 'Integrate Applications with Gemini on Google Cloud', min: 105 },
  { id: 1123, name: 'Conversational Insights', min: 105 },
  { id: 1153, name: 'Modern Security Operations', min: 105 },
  { id: 1193, name: 'AI Services and GDC Deployments and Operations', min: 105 },
  { id: 1198, name: 'Compute, Network, and Storage Services Configuration in GDC', min: 105 },
  { id: 1266, name: 'Gen AI Apps: Transform Your Work', min: 105 },
  { id: 1519, name: 'Introduction to Google Security Operations: Unified SecOps', min: 105 },
  { id: 1760, name: 'Build a Certification Study Guide: ADP Exam Prep', min: 105 },
  { id: 388, name: 'Responsible AI: Applying AI Principles with Google Cloud', min: 120 },
  { id: 552, name: 'Introduction to Vertex AI Studio', min: 120 },
  { id: 703, name: 'Getting Started with Apache Kafka and Confluent Platform on Google Cloud', min: 120 },
  { id: 717, name: 'DevOps Essentials', min: 120 },
  { id: 732, name: 'Google Kubernetes Engine Best Practices: Security', min: 120 },
  { id: 767, name: 'Optimize Your Google Cloud Costs', min: 120 },
  { id: 879, name: 'Gemini for Data Scientists and Analysts', min: 120 },
  { id: 945, name: 'Trust and Security with Google Cloud', min: 120 },
  { id: 957, name: 'Google Cloud Customer Care Fundamentals', min: 120 },
  { id: 1069, name: 'Responsible AI for Digital Leaders with Google Cloud', min: 120 },
  { id: 1097, name: 'Website Modernization with Generative AI on Google Cloud', min: 120 },
  { id: 1124, name: 'Create Conversational Agents with Stateful Flows', min: 120 },
  { id: 1158, name: 'Introduction to Reliable Deep Learning', min: 120 },
  { id: 1159, name: 'Agent Assist and its Gen AI Capabilities', min: 120 },
  { id: 1166, name: 'Streamline App Development with Gemini Code Assist', min: 120 },
  { id: 1185, name: 'Looker Studio Pro Essentials', min: 120 },
  { id: 1192, name: 'GDC Platform Introduction', min: 120 },
  { id: 1210, name: 'Create Embeddings, Vector Search, and RAG with BigQuery', min: 120 },
  { id: 1413, name: 'Secure GKE with Cloud Next Generation Firewall', min: 120 },
  { id: 1510, name: 'Troubleshooting with AI Using Cloud Assist Investigations', min: 120 },
  { id: 1571, name: 'Security Command Center: Vulnerabilities and Misconfigurations', min: 120 },
  { id: 1668, name: 'AI-powered Database Management with Gemini', min: 120 },
  { id: 1828, name: 'Configure VPC Routes and Addresses', min: 120 },
  { id: 940, name: 'Using DevSecOps in your Google Cloud Environment', min: 135 },
  { id: 1267, name: 'Gen AI Agents: Transform Your Organization', min: 135 },
  { id: 1401, name: 'Introduction to Gemini Enterprise', min: 135 },
  { id: 1832, name: 'Build Agent Skills with Google', min: 135 },
  { id: 516, name: 'Google Chat', min: 150 },
  { id: 621, name: 'Google Cloud Essentials', min: 150 },
  { id: 723, name: 'Generative AI Explorer - Agent Platform', min: 150 },
  { id: 740, name: 'Intro to ML: Language Processing', min: 150 },
  { id: 781, name: 'Workspace: Add-ons', min: 150 },
  { id: 1080, name: 'Machine Learning Operations (MLOps) with Agent Platform: Model Evaluation', min: 150 },
  { id: 1144, name: 'Networking in Google Cloud: Network Architecture', min: 150 },
  { id: 1381, name: 'Introduction to Looker', min: 150 },
  { id: 1385, name: 'Model Armor: Securing AI Deployments', min: 150 },
  { id: 1462, name: 'Introduction Google Security Operations (SOAR)', min: 150 },
  { id: 1680, name: 'Optimize VPC Traffic with Flow Analyzer', min: 150 },
  { id: 1685, name: 'Liftoff with Google Antigravity: Build a Video Game with AI', min: 150 },
  { id: 91, name: 'Google Workspace Data Governance', min: 165 },
  { id: 417, name: 'Role Based Learning Path: Citizen Developer', min: 165 },
  { id: 785, name: 'Securing your Network with Cloud Armor', min: 165 },
  { id: 1145, name: 'Networking in Google Cloud: Hybrid and Multicloud', min: 165 },
  { id: 1264, name: 'Migrate your VPC Firewall Policies to Cloud NGFW', min: 165 },
  { id: 1576, name: 'GKE Routing and IP Address Management', min: 165 },
  { id: 218, name: 'Serverless Data Processing with Dataflow: Foundations', min: 180 },
  { id: 578, name: 'Introduction to Data Analytics on Google Cloud', min: 180 },
  { id: 620, name: 'Baseline: Infrastructure', min: 180 },
  { id: 739, name: 'Intro to ML: Image Processing', min: 180 },
  { id: 762, name: 'NCAA® March Madness®: Bracketology with Google Cloud', min: 180 },
  { id: 989, name: 'Responsible AI for Developers: Interpretability & Transparency', min: 180 },
  { id: 1060, name: 'Using BigQuery Machine Learning for Inference', min: 180 },
  { id: 1133, name: 'Work with Gemini Models in BigQuery', min: 180 },
  { id: 1143, name: 'Networking in Google Cloud: Load Balancing', min: 180 },
  { id: 1309, name: 'Implement Cloud Next Generation Firewall', min: 180 },
  { id: 1410, name: 'Data Governance with Dataplex Universal Catalog', min: 180 },
  { id: 1559, name: 'Unlock Insights with Gemini Notebook', min: 180 },
  { id: 1560, name: 'Google Cloud Database Migrations: Strategy', min: 180 },
  { id: 1619, name: 'AI Fundamentals', min: 180 },
  { id: 1637, name: 'Google Cloud Database Migrations: Homogeneous', min: 180 },
  { id: 1659, name: 'Google Cloud Database Migrations: Heterogeneous', min: 180 },
  { id: 1672, name: 'Agentic Strategy: Discover, Design, and Prototype', min: 180 },
  { id: 1683, name: 'Google AI for Finance Professionals', min: 180 },
  { id: 44, name: 'Introduction to Cloud Identity', min: 195 },
  { id: 720, name: 'Flutter Development', min: 195 },
  { id: 730, name: 'Getting Started with Go on Google Cloud', min: 195 },
  { id: 1162, name: 'Build AI Agents with Agent Platform and Flutter', min: 195 },
  { id: 779, name: 'Google Workspace Essentials', min: 210 },
  { id: 675, name: 'Baseline: Deploy & Develop', min: 225 },
  { id: 729, name: 'Getting Started with Datadog on Google Cloud', min: 225 },
  { id: 746, name: 'Managing Cloud Infrastructure with Terraform', min: 225 },
  { id: 1197, name: 'SecOps on GDC for Tier 3 Analysts', min: 225 },
  { id: 1280, name: 'Google Workspace Troubleshooting', min: 225 },
  { id: 1373, name: 'Introduction to reCAPTCHA', min: 225 },
  { id: 1733, name: 'Looker Core Administration', min: 225 },
  { id: 465, name: 'Service Orchestration and Choreography on Google Cloud', min: 240 },
  { id: 680, name: 'BigQuery for Machine Learning', min: 240 },
  { id: 682, name: 'Website on Google Cloud', min: 240 },
  { id: 689, name: 'Building No-Code AppSheet Apps', min: 240 },
  { id: 699, name: 'Using the Cloud SDK Command Line', min: 240 },
  { id: 939, name: 'Vector Search and Embeddings', min: 240 },
  { id: 958, name: 'Manage Functions and Reporting with CCaaS', min: 240 },
  { id: 960, name: 'Getting Started with Security Command Center Enterprise', min: 240 },
  { id: 985, name: 'Responsible AI for Developers: Fairness & Bias', min: 240 },
  { id: 1120, name: 'Create Generative AI Apps on Google Cloud', min: 240 },
  { id: 1127, name: 'Google Cloud VMware Engine Fundamentals', min: 240 },
  { id: 1169, name: 'Boost Productivity with Gemini in BigQuery', min: 240 },
  { id: 1321, name: 'Generate and Edit Media in Agent Platform', min: 240 },
  { id: 1368, name: 'Supervised Fine-tuning for Gemini', min: 240 },
  { id: 1379, name: 'Looker Studio Essentials', min: 240 },
  { id: 1436, name: 'Build AI Agents with Enterprise Databases', min: 240 },
  { id: 1450, name: 'Google DeepMind: 03 Design And Train Neural Networks', min: 240 },
  { id: 1451, name: 'Google DeepMind: 04 Discover The Transformer Architecture', min: 240 },
  { id: 1452, name: 'Google DeepMind: 02 Represent Your Language Data', min: 240 },
  { id: 52, name: 'Build Streaming Data Pipelines on Google Cloud', min: 255 },
  { id: 391, name: 'Vertex AI Search for Commerce', min: 255 },
  { id: 567, name: 'Google Security Operations - SOAR Analyst', min: 255 },
  { id: 1515, name: 'Foundations of Identity and Access Management', min: 255 },
  { id: 90, name: 'Google Workspace User and Resource Management', min: 270 },
  { id: 158, name: 'Machine Learning Operations (MLOps): Getting Started', min: 270 },
  { id: 195, name: 'Google Docs', min: 270 },
  { id: 707, name: 'Creating Infrastructure on Google Cloud with Terraform', min: 270 },
  { id: 764, name: 'Automate Deployment and Manage Traffic on a Google Cloud Network', min: 270 },
  { id: 774, name: 'Understanding LookML in Looker', min: 270 },
  { id: 1068, name: 'Introduction to ChromeOS Administration', min: 270 },
  { id: 201, name: 'Google Calendar', min: 285 },
  { id: 1199, name: 'Introduction to SecOps on GDC', min: 285 },
  { id: 1224, name: 'Google AI Essentials', min: 285 },
  { id: 35, name: 'Networking in Google Cloud: Fundamentals', min: 300 },
  { id: 36, name: 'Networking in Google Cloud: Routing and Addressing', min: 300 },
  { id: 54, name: 'Build Data Lakes and Data Warehouses on Google Cloud', min: 300 },
  { id: 60, name: 'Google Cloud Fundamentals: Core Infrastructure', min: 300 },
  { id: 72, name: 'Preparing for your Professional Data Engineer Journey', min: 300 },
  { id: 88, name: 'Mitigating Security Vulnerabilities on Google Cloud', min: 300 },
  { id: 517, name: 'Google Cloud AI and ML Solutions for the Public Sector', min: 300 },
  { id: 530, name: 'Developing Containerized Applications on Google Cloud', min: 300 },
  { id: 577, name: 'Google Agile Essentials', min: 300 },
  { id: 584, name: 'MLOps with Agent Platform: Manage Features', min: 300 },
  { id: 695, name: 'Cloud Engineering', min: 300 },
  { id: 698, name: 'Cloud Logging', min: 300 },
  { id: 773, name: 'Transform and Clean your Data with Dataprep by Alteryx on Google Cloud', min: 300 },
  { id: 865, name: 'BigQuery for Data Analysts', min: 300 },
  { id: 892, name: 'Conversational AI on Vertex AI and Dialogflow CX', min: 300 },
  { id: 1036, name: 'Responsible AI for Developers: Privacy & Safety', min: 300 },
  { id: 1191, name: 'Accelerate Knowledge Exchange with Gemini Enterprise', min: 300 },
  { id: 1600, name: 'Customer Experience Agent Studio: Fundamentals', min: 300 },
  { id: 1627, name: 'Introduction to Google Security Operations (SIEM)', min: 300 },
  { id: 1782, name: 'AgentOps: Operationalize AI Agents on Google Cloud', min: 300 },
  { id: 744, name: 'Kubernetes in Google Cloud', min: 315 },
  { id: 758, name: 'Migrating MySQL data to Cloud SQL using Database Migration Service', min: 315 },
  { id: 777, name: 'Using Vault on Google Cloud', min: 315 },
  { id: 198, name: 'Google Meet', min: 330 },
  { id: 199, name: 'Google Drive', min: 330 },
  { id: 336, name: 'Building No-Code Apps with AppSheet: Foundations', min: 330 },
  { id: 697, name: 'Cloud Healthcare API', min: 330 },
  { id: 721, name: 'Flutter Essentials', min: 330 },
  { id: 731, name: 'Getting Started with MongoDB Atlas on Google Cloud', min: 330 },
  { id: 1195, name: 'SecOps on GDC for Tier 1 and Tier 2 Analysts', min: 330 },
  { id: 2, name: 'Getting Started with Google Kubernetes Engine', min: 345 },
  { id: 323, name: 'Analyzing and Visualizing Data in Looker', min: 345 },
  { id: 1713, name: 'BigQuery for Data Scientists', min: 345 },
  { id: 1786, name: 'Orchestrate Workflows with the Data Agent Kit', min: 345 },
  { id: 449, name: 'Building No-Code Apps with AppSheet: Automation', min: 360 },
  { id: 1189, name: 'Build Generative AI Apps with Firebase Genkit', min: 360 },
  { id: 1229, name: 'Google Prompting Essentials', min: 360 },
  { id: 1234, name: 'Select a Google Cloud Database for Your Applications', min: 360 },
  { id: 1275, name: 'Deploy Multi-Agent Systems with Gemini Enterprise Agent Platform', min: 360 },
  { id: 1331, name: 'Google Advanced Data Analytics Capstone', min: 360 },
  { id: 1341, name: 'Google DeepMind: 01 Build Your Own Small Language Model', min: 360 },
  { id: 1383, name: 'Accelerate Your Job Search with AI', min: 360 },
  { id: 1667, name: 'Orchestrate ML Workflows with Agent Platform', min: 360 },
  { id: 701, name: 'Cloud SQL', min: 375 },
  { id: 724, name: 'Getting Started with Apache Beam', min: 375 },
  { id: 1142, name: 'Networking in Google Cloud: Network Security', min: 375 },
  { id: 1582, name: 'Vibe Coding for Beginners: From Zero to App', min: 375 },
  { id: 33, name: 'Architecting with Google Kubernetes Engine: Production', min: 390 },
  { id: 34, name: 'Architecting with Google Kubernetes Engine: Workloads', min: 390 },
  { id: 48, name: 'Google Workspace Security', min: 390 },
  { id: 196, name: 'Google Sheets', min: 390 },
  { id: 443, name: 'Getting Started with Terraform for Google Cloud', min: 390 },
  { id: 864, name: 'Observability in Google Cloud', min: 390 },
  { id: 50, name: 'Essential Google Cloud Infrastructure: Foundation', min: 405 },
  { id: 874, name: 'Developing Applications with Google Cloud: Foundations', min: 405 },
  { id: 55, name: 'Smart Analytics, Machine Learning, and AI on Google Cloud', min: 420 },
  { id: 178, name: 'Elastic Google Cloud Infrastructure: Scaling and Automation', min: 420 },
  { id: 327, name: 'Developing Data Models with LookML', min: 420 },
  { id: 1555, name: 'Google DeepMind: 07 Accelerate Your Model', min: 420 },
  { id: 200, name: 'Gmail', min: 435 },
  { id: 505, name: 'Developing Applications with Cloud Run Functions on Google Cloud', min: 435 },
  { id: 1746, name: 'Craft ADK Agents with Persistent Memories', min: 435 },
  { id: 18, name: 'Computer Vision Fundamentals with Google Cloud', min: 480 },
  { id: 39, name: 'Recommendation Systems on Google Cloud', min: 480 },
  { id: 40, name: 'Natural Language Processing on Google Cloud', min: 480 },
  { id: 95, name: 'Developing a Google SRE Culture', min: 480 },
  { id: 153, name: 'Google Cloud Computing Foundations: Cloud Computing Fundamentals', min: 480 },
  { id: 167, name: 'Architecting and Installing the Apigee Hybrid API Platform', min: 480 },
  { id: 169, name: 'Upgrading and Monitoring the Apigee Hybrid API Platform', min: 480 },
  { id: 180, name: 'Networking in Google Cloud: Hands-On Practice', min: 480 },
  { id: 280, name: 'Innovating with Data and Google Cloud', min: 480 },
  { id: 293, name: 'Google Sheets - Advanced Topics', min: 480 },
  { id: 480, name: 'Analyzing and Visualizing Data the Google Way', min: 480 },
  { id: 501, name: 'Google Cloud Data Solutions for the Public Sector', min: 480 },
  { id: 502, name: 'Google Cloud Security for the Public Sector', min: 480 },
  { id: 506, name: 'Modernizing Retail and Ecommerce Solutions with Google Cloud', min: 480 },
  { id: 513, name: 'BigQuery Fundamentals for Teradata Professionals', min: 480 },
  { id: 515, name: 'BigQuery Fundamentals for Oracle Professionals', min: 480 },
  { id: 518, name: 'Planetary Scale Earth Observation with Google Earth Engine', min: 480 },
  { id: 520, name: 'Google Cloud IAM and Networking for Azure Professionals', min: 480 },
  { id: 522, name: 'Google Cloud IAM and Networking for AWS Professionals', min: 480 },
  { id: 523, name: 'Deploy and Monitor in Google Cloud for AWS Professionals', min: 480 },
  { id: 524, name: 'Deploy and Monitor in Google Cloud for Azure Professionals', min: 480 },
  { id: 525, name: 'Google Cloud Compute and Scalability for Azure Professionals', min: 480 },
  { id: 526, name: 'Google Cloud Compute and Scalability for AWS Professionals', min: 480 },
  { id: 531, name: 'Building Applications with Eventarc on Google Cloud', min: 480 },
  { id: 559, name: 'Developing Applications with Cloud Run on Google Cloud: Fundamentals', min: 480 },
  { id: 560, name: 'MySQL to Cloud Spanner', min: 480 },
  { id: 565, name: 'AppSheet Team Hierarchy', min: 480 },
  { id: 593, name: 'Introduction to AI and Machine Learning on Google Cloud', min: 480 },
  { id: 612, name: 'Enterprise Search on Generative AI App Builder', min: 480 },
  { id: 660, name: 'Configure Google Kubernetes Engine Networking', min: 480 },
  { id: 869, name: 'Chronicle SOAR Fundamentals - Locales', min: 480 },
  { id: 875, name: 'AppSheet Administration', min: 480 },
  { id: 1186, name: 'Google Threat Intelligence', min: 480 },
  { id: 1504, name: 'Understand Google Cloud Agents', min: 480 },
  { id: 1522, name: 'Google People Management Essentials', min: 480 },
  { id: 1556, name: 'Google DeepMind: 05 Fine-Tune Your Model', min: 480 },
  { id: 49, name: 'Essential Google Cloud Infrastructure: Core Services', min: 495 },
  { id: 21, name: 'Managing Security in Google Cloud', min: 510 },
  { id: 99, name: 'Logging and Monitoring in Google Cloud', min: 510 },
  { id: 154, name: 'Google Cloud Computing Foundations: Infrastructure in Google Cloud', min: 510 },
  { id: 155, name: 'Google Cloud Computing Foundations: Networking & Security in Google Cloud', min: 510 },
  { id: 156, name: 'Google Cloud Computing Foundations: Data, ML, and AI in Google Cloud', min: 510 },
  { id: 197, name: 'Google Slides', min: 510 },
  { id: 397, name: 'Preparing for Your Professional Cloud Security Engineer Journey', min: 510 },
  { id: 616, name: 'Understanding Cloud Spanner', min: 510 },
  { id: 770, name: 'Security & Identity Fundamentals', min: 510 },
  { id: 1029, name: 'Configure and Maintain CCaaS as an Admin', min: 510 },
  { id: 1382, name: 'Build intelligent agents with Agent Development Kit (ADK)', min: 510 },
  { id: 254, name: 'API Design and Fundamentals with the Apigee API Platform', min: 540 },
  { id: 1215, name: 'Play It Safe: Manage Security Risks', min: 540 },
  { id: 53, name: 'Build Batch Data Pipelines on Google Cloud', min: 555 },
  { id: 92, name: 'Google Workspace Core Services', min: 555 },
  { id: 693, name: 'Building Codeless Pipelines on Cloud Data Fusion', min: 555 },
  { id: 1157, name: 'Introduction to Data Engineering on Google Cloud', min: 570 },
  { id: 255, name: 'API Security with the Apigee API Platform', min: 600 },
  { id: 1214, name: 'Foundations of Cybersecurity', min: 600 },
  { id: 1216, name: 'Connect and Protect: Networks and Network Security', min: 600 },
  { id: 1220, name: 'Put It to Work: Prepare for Cybersecurity Jobs', min: 600 },
  { id: 1255, name: 'Foundations of Project Management', min: 600 },
  { id: 1231, name: 'Google Data Analytics Capstone: Complete a case study', min: 660 },
  { id: 1305, name: 'Put It All Together: Prepare for a Cloud Security Analyst Job', min: 660 },
  { id: 1332, name: 'Build Wireframes and Low-Fidelity Prototypes', min: 660 },
  { id: 87, name: 'Security Best Practices in Google Cloud', min: 675 },
  { id: 1034, name: 'L300 Google Distributed Cloud air-gapped', min: 720 },
  { id: 1222, name: 'Foundations: Data, Data, Everywhere', min: 720 },
  { id: 1271, name: 'Foundations of Digital Marketing and E-commerce', min: 720 },
  { id: 1298, name: 'Put It All Together: Prepare for a Cloud Data Analyst Job', min: 720 },
  { id: 1283, name: 'Foundations of User Experience (UX) Design', min: 780 },
  { id: 1287, name: 'Design a User Experience for Social Good & Prepare for Jobs', min: 780 },
  { id: 41, name: 'Reliable Google Cloud Infrastructure: Design and Process', min: 840 },
  { id: 1262, name: 'Attract and Engage Customers with Digital Marketing', min: 840 },
  { id: 1290, name: 'Conduct UX Research and Test Early Concepts', min: 840 },
  { id: 1317, name: 'Foundations of Business Intelligence', min: 840 },
  { id: 264, name: 'Serverless Data Processing with Dataflow: Operations', min: 885 },
  { id: 1223, name: 'Ask Questions to Make Data-Driven Decisions', min: 900 },
  { id: 1272, name: 'Satisfaction Guaranteed: Develop Customer Loyalty Online', min: 900 },
  { id: 1284, name: 'Foundations of Data Science', min: 900 },
  { id: 1307, name: 'Make the Sale: Build, Launch, and Manage E-commerce Stores', min: 900 },
  { id: 1557, name: 'Google DeepMind : 08 Capstone: Develop Your Model for Real-World Impact', min: 900 },
  { id: 17, name: 'Production Machine Learning Systems', min: 960 },
  { id: 512, name: 'BigQuery Fundamentals for Redshift Professionals', min: 960 },
  { id: 514, name: 'BigQuery Fundamentals for Snowflake Professionals', min: 960 },
  { id: 519, name: 'Google Cloud Storage and Containers for AWS Professionals', min: 960 },
  { id: 521, name: 'Google Cloud Storage and Containers for Azure Professionals', min: 960 },
  { id: 535, name: 'Serving Multimedia Content with Google Cloud', min: 960 },
  { id: 1061, name: 'Change Management for Google Workspace', min: 960 },
  { id: 1228, name: 'Process Data from Dirty to Clean', min: 960 },
  { id: 1256, name: 'Project Initiation: Starting a Successful Project', min: 960 },
  { id: 1282, name: 'Build Dynamic User Interfaces (UI) for Websites', min: 960 },
  { id: 1328, name: 'The Path to Insights: Data Models and Pipelines', min: 960 },
  { id: 1344, name: 'Automating Real-World Tasks with Python', min: 1020 },
  { id: 256, name: 'API Development with the Apigee API Platform', min: 1080 },
  { id: 1225, name: 'Prepare Data for Exploration', min: 1080 },
  { id: 1227, name: 'Share Data Through the Art of Visualization', min: 1080 },
  { id: 1259, name: 'Agile Project Management', min: 1080 },
  { id: 1273, name: 'Think Outside the Inbox: Email Marketing', min: 1080 },
  { id: 1281, name: 'Assess for Success: Marketing Analytics and Measurement', min: 1080 },
  { id: 1295, name: 'Introduction to Data Analytics in Google Cloud', min: 1080 },
  { id: 1296, name: 'Data Transformation in the Cloud', min: 1080 },
  { id: 1329, name: 'Decisions, Decisions: Dashboards and Reports', min: 1080 },
  { id: 1339, name: 'Configuration Management and the Cloud', min: 1080 },
  { id: 1300, name: 'Introduction to Security Principles in Cloud Computing', min: 1095 },
  { id: 1251, name: 'Technical Support Fundamentals', min: 1140 },
  { id: 1308, name: 'Create High-Fidelity Designs and Prototypes in Figma', min: 1140 },
  { id: 1342, name: 'Troubleshooting and Debugging Techniques', min: 1140 },
  { id: 1217, name: 'Assets, Threats, and Vulnerabilities', min: 1200 },
  { id: 1218, name: 'Sound the Alarm: Detection and Response', min: 1200 },
  { id: 1219, name: 'Automate Cybersecurity Tasks with Python', min: 1200 },
  { id: 1221, name: 'Tools of the Trade: Linux and SQL', min: 1200 },
  { id: 1285, name: 'Start the UX Design Process: Empathize, Define, and Ideate', min: 1200 },
  { id: 1343, name: 'Introduction to Git and GitHub', min: 1200 },
  { id: 1348, name: 'Crash Course on Python', min: 1200 },
  { id: 229, name: 'Serverless Data Processing with Dataflow: Develop Pipelines', min: 1260 },
  { id: 1252, name: 'The Bits and Bytes of Computer Networking', min: 1260 },
  { id: 1257, name: 'Project Planning: Putting It All Together', min: 1260 },
  { id: 1258, name: 'Project Execution: Running the Project', min: 1260 },
  { id: 1279, name: 'From Likes to Leads: Interact with Customers Online', min: 1260 },
  { id: 1301, name: 'Strategies for Cloud Security Risk Management', min: 1305 },
  { id: 1270, name: 'IT Security: Defense against the digital dark arts', min: 1320 },
  { id: 32, name: 'Architecting with Google Kubernetes Engine: Foundations', min: 1440 },
  { id: 390, name: 'Building No-Code Apps with AppSheet: Implementation', min: 1440 },
  { id: 511, name: 'Introduction to Vertex Forecasting and Time Series in Practice', min: 1440 },
  { id: 1254, name: 'System Administration and IT Infrastructure Services', min: 1440 },
  { id: 1230, name: 'Analyze Data to Answer Questions', min: 1560 },
  { id: 1303, name: 'Detect, Respond, and Recover from Cloud Cybersecurity Attacks', min: 1575 },
  { id: 1304, name: 'Data Management and Storage in the Cloud', min: 1575 },
  { id: 1226, name: 'Introduction to Data Analysis Using Python', min: 1620 },
  { id: 1253, name: 'Operating Systems and You: Becoming a Power User', min: 1620 },
  { id: 1297, name: 'The Power of Storytelling: How to Visualize Data in the Cloud', min: 1620 },
  { id: 1330, name: 'Go Beyond the Numbers: Translate Data into Insights', min: 1620 },
  { id: 1302, name: 'Cloud Security Risks: Identify and Protect Against Threats', min: 1680 },
  { id: 1311, name: 'Regression Analysis: Simplify Complex Data Relationships', min: 1680 },
  { id: 1314, name: 'The Power of Statistics', min: 1860 },
  { id: 1338, name: 'Using Python to Interact with the Operating System', min: 1920 },
  { id: 1315, name: 'The Nuts and Bolts of Machine Learning', min: 2040 },
  { id: 1277, name: 'Capstone: Applying Project Management in the Real World', min: 2280 },
  { id: 1501, name: 'Manage Scalable Workloads in GKE', min: 4320 },
]
